// Prototype only. Legal-card and trick bookkeeping are local; result labels and contract tables are intentionally canned, never a solver.
const seats=['N','E','S','W'], names={N:'北',E:'东',S:'南',W:'西'}, suits=['S','H','D','C'], symbols={S:'♠',H:'♥',D:'♦',C:'♣'}, ranks='AKQJT98765432';
const example={N:['AKT972','-','Q742','Q84'],E:['43','KQT7','J65','AJ92'],S:['J865','964','K','KT763'],W:['Q','AJ8532','AT983','5']};
const clone=x=>JSON.parse(JSON.stringify(x));
const toCards=raw=>Object.fromEntries(seats.map(s=>[s,suits.flatMap((suit,i)=>[...raw[s][i]].filter(r=>ranks.includes(r)).map(r=>({suit,rank:r,id:suit+r})))]));
const variants={A:{name:'左上角叫牌小表 · 已选',question:'A · 已确认采用角落叫牌小表。手牌改为紧凑牌点行；点牌与合法牌上的逐牌结果保留。'},B:{name:'桌边折叠记录',question:'B · 叫牌默认收成桌边入口，点开浮层查看。桌心与四家最干净；需要多一次点击才能查看完整记录。'},C:{name:'桌下叫牌条',question:'C · 叫牌挪到桌下横条，默认留一行摘要，展开完整四列。桌面更聚焦；完整记录增加纵向占用。'}};
let variant=new URLSearchParams(location.search).get('variant')||'A';if(!variants[variant])variant='A';
let raw=clone(example),original=toCards(raw),visible=new Set(['N','W']),version=1,tableVersion=1,shownResults=false,auctionOpen=false,teachingGenerated=false;
let game=fresh(),undo=[],redo=[];
function fresh(){return {started:false,hands:clone(original),trick:[],leader:'N',turn:'N',ns:0,ew:0,completed:0,lastWinner:null};}
function complete(){const all=seats.flatMap(s=>original[s]);return seats.every(s=>original[s].length===13)&&new Set(all.map(c=>c.id)).size===52;}
function currentLegal(){if(!game.started||game.trick.length===4||game.completed===13)return [];const hand=game.hands[game.turn],lead=game.trick[0]?.card.suit;return lead&&hand.some(c=>c.suit===lead)?hand.filter(c=>c.suit===lead):hand;}
function rankValue(r){return 14-ranks.indexOf(r);}
function winner(){const lead=game.trick[0].card.suit;return game.trick.reduce((best,p)=>{const value=c=>(c.suit==='H'?100:c.suit===lead?50:0)+rankValue(c.rank);return value(p.card)>value(best.card)?p:best;}).seat;}
function change(fn){undo.push(clone(game));redo=[];fn();render();}
function resultFor(card){const values=['=','−1','+1','−2','+2'];return values[(ranks.indexOf(card.rank)+suits.indexOf(card.suit)+game.completed+game.trick.length)%values.length];}
function auctionTable(){return '<table aria-label="示例叫牌记录"><thead><tr><th>北</th><th>东</th><th>南</th><th>西</th></tr></thead><tbody><tr><td>Pass</td><td>Pass</td><td>Pass</td><td class="red">1♥</td></tr><tr><td>Pass</td><td class="red">3♥</td><td>Pass</td><td class="red">5♥</td></tr><tr><td>Pass</td><td>Pass</td><td>Pass</td><td></td></tr></tbody></table>';}
function renderHand(s){const legal=s===game.turn?currentLegal().map(c=>c.id):[],cards=game.started?game.hands[s]:original[s];return `<div class="hand ${s} ${game.started&&s===game.turn&&game.trick.length<4&&game.completed<13?'active':''}"><div class="hand-head"><span class="seat-letter">${s}</span><strong>${names[s]}家</strong>${s==='W'?'<span class="role">庄</span>':''}<label class="visibility"><input type="checkbox" data-visibility="${s}" ${visible.has(s)?'checked':''} aria-label="${names[s]}家教学可见">教学可见</label></div>${suits.map(suit=>`<div class="suit-row"><span class="suit-symbol ${['H','D'].includes(suit)?'red':''}">${symbols[suit]}</span><div class="cards">${cards.filter(c=>c.suit===suit).map(c=>{const ok=legal.includes(c.id),res=resultFor(c);return `<button class="card ${ok?'legal':''} ${['H','D'].includes(suit)?'red':''}" data-card="${c.id}" data-seat="${s}" ${ok?'':'disabled'} aria-label="${names[s]}家 ${symbols[suit]}${c.rank==='T'?'10':c.rank}${shownResults&&ok?' 模拟结果 '+res:''}"><span>${c.rank==='T'?'10':c.rank}</span>${shownResults&&ok?`<span class="result ${res.includes('−')?'minus':''}">${res}</span>`:''}</button>`;}).join('')||`<span class="unknown">${original[s].length?'—':'未知'}</span>`}</div></div>`).join('')}</div>`;}
function renderTrick(){let caption=!game.started?'用户控制四家点牌':game.completed===13?'示例推演结束':game.trick.length===4?`${names[winner()]}家赢墩 · 待收起`:`轮到${names[game.turn]}家 · ${game.trick.length?'须跟'+symbols[game.trick[0].card.suit]+'（有该花色时）':'自由首引'}`;return `<div class="trick"><div class="trick-caption">当前墩 · 第 ${Math.min(13,game.completed+1)} 墩</div><div class="trick-title">${caption}</div><div class="trick-cards">${game.trick.length?game.trick.map(p=>`<div class="played ${p.seat} ${['H','D'].includes(p.card.suit)?'red':''}">${symbols[p.card.suit]}${p.card.rank==='T'?'10':p.card.rank}<small>${names[p.seat]}家</small></div>`).join(''):'<span class="empty">四张牌在这里汇合</span>'}</div>${game.trick.length===4?'<button data-action="collect" class="primary">收起本墩 · 候选</button>':'<span class="small">'+(game.started?'轮到的一家可点牌':complete()?'点击上方“开始自主推演”':'补齐四手后才可推演')+'</span>'}</div>`;}
function render(){
 document.body.dataset.variant=variant;document.body.classList.toggle('show-results',shownResults);
 const corner=variant==='A'?`<div class="auction-corner auction-box"><div class="auction-head"><strong>叫牌已结束</strong><button data-action="auction">${auctionOpen?'收起':'展开'}</button></div>${auctionOpen?auctionTable():'<div class="auction-mini">5<span class="red">♥</span> 西 · 11 个叫品</div>'}</div>`:variant==='B'?'<div class="auction-fold"><button data-action="auction-modal">☷ 叫牌记录 · 11</button></div>':'';
 document.querySelector('#board').innerHTML=corner+seats.map(renderHand).join('')+renderTrick();
 document.querySelector('#auction-strip').innerHTML=variant==='C'?`<div class="auction-rail"><strong>叫牌记录</strong><span class="rail-calls">… 3♥ · Pass · 5♥ · Pass · Pass · Pass</span><button data-action="auction">${auctionOpen?'收起':'展开'}</button></div>${auctionOpen?'<div class="auction-box">'+auctionTable()+'</div>':''}`:'';
 document.querySelector('#gate').textContent=complete()?(game.started?'只点亮当前行动家的合法牌 · 每张牌的数值均为模拟':'四手已录齐（52 张）· 点击“开始自主推演”后可点牌；教学仍按勾选手牌'):`已录 ${seats.filter(s=>original[s].length===13).map(s=>names[s]).join('／')||'零'} 家 · 补齐 ${seats.filter(s=>original[s].length!==13).map(s=>names[s]).join('／')} 家各 13 张后才可推演；仍可生成做庄教学`;
 document.querySelector('#start').disabled=!complete()||game.started;document.querySelector('#start').textContent=game.started?'推演进行中':'开始自主推演';
 document.querySelector('#dd').disabled=!complete();document.querySelector('#results').disabled=!complete();document.querySelector('#results').checked=shownResults;
 document.querySelector('#undo').disabled=!undo.length;document.querySelector('#redo').disabled=!redo.length;document.querySelector('#restart').disabled=!game.started;
 document.querySelector('#score').textContent=`已收 ${game.completed} 墩　NS ${game.ns} · EW ${game.ew}`;
 const legal=currentLegal().map(c=>symbols[c.suit]+(c.rank==='T'?'10':c.rank)).join(' ');
 document.querySelector('#state').textContent=`原始四手 v${version} · 已录 ${seats.map(s=>names[s]+original[s].length).join(' / ')}　｜　教学：${[...visible].map(s=>names[s]).join('、')||'未选'}　｜　${game.started?'行动：'+(game.trick.length===4?'待收墩':names[game.turn])+' · 合法牌：'+(legal||'—'):'推演未开始'}　｜　定约表：${!complete()?'输入不足':tableVersion===version?'v'+tableVersion+'（固定演示）':'旧结果失效'}`;
 document.querySelector('#variant-label').textContent=variant+' · '+variants[variant].name;document.querySelector('#variant-question').textContent=variants[variant].question;
 renderTeaching();
 document.querySelectorAll('[data-visibility]').forEach(el=>el.onchange=()=>{el.checked?visible.add(el.dataset.visibility):visible.delete(el.dataset.visibility);teachingGenerated=false;render();});
 document.querySelectorAll('[data-card]').forEach(el=>el.onclick=()=>{const seat=el.dataset.seat,id=el.dataset.card;if(seat!==game.turn||!currentLegal().some(c=>c.id===id))return;change(()=>{const card=game.hands[seat].find(c=>c.id===id);game.hands[seat]=game.hands[seat].filter(c=>c.id!==id);game.trick.push({seat,card});game.turn=seats[(seats.indexOf(seat)+1)%4];});});
 document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>{if(el.dataset.action==='collect'){change(()=>{const w=winner();['N','S'].includes(w)?game.ns++:game.ew++;game.completed++;game.lastWinner=w;game.leader=w;game.turn=w;game.trick=[];});}else if(el.dataset.action==='auction'){auctionOpen=!auctionOpen;render();}else showModal('叫牌记录 · 示例',auctionTable()+'<p>完整记录与中央当前墩分开。此原型只查看，不编辑叫牌。</p>');});
}
function renderTeaching(){const scope=[...visible].map(s=>names[s]+'家').join('、')||'未勾选手牌';document.querySelector('#teaching-content').innerHTML=`<div class="teaching-empty"><div class="book-icon">▤</div><h3>${teachingGenerated?'本次教学只使用勾选手牌':'你的做庄计划会显示在这里'}</h3><p>${teachingGenerated?'演示请求已接收。实际教学输出未实现；本页只验证输入边界。':'填写定约、庄家手牌和其他当时可见的信息，然后生成一份具体路线。未提供的手牌作为未知。'}</p><div class="teaching-scope">教学可见：${scope} · 共 ${visible.size} 家</div><p>原始牌面已录 ${seats.filter(s=>original[s].length===13).length} 手。勾选只影响教学信息，不改变推演资格。</p>${teachingGenerated?'<div class="mock-note">模拟教学回执 · 未调用模型，不提供虚构的打法建议。</div>':''}</div>`;}
function showModal(title,html){document.querySelector('#modal-title').textContent=title;document.querySelector('#modal-content').innerHTML=html;document.querySelector('#modal').showModal();}
function switchVariant(delta){const keys=Object.keys(variants);variant=keys[(keys.indexOf(variant)+delta+3)%3];const url=new URL(location.href);url.searchParams.set('variant',variant);history.replaceState({},'',url);auctionOpen=false;render();}
function load(partial){raw=clone(example);if(partial){raw.E=['','','',''];raw.S=['','','',''];}original=toCards(raw);version++;tableVersion=complete()?version:null;game=fresh();undo=[];redo=[];shownResults=false;auctionOpen=false;teachingGenerated=false;render();}
document.querySelector('#full').onclick=()=>load(false);document.querySelector('#partial').onclick=()=>load(true);
document.querySelector('#start').onclick=()=>{if(complete())change(()=>{game.started=true;});};
document.querySelector('#results').onchange=e=>{shownResults=e.target.checked;render();};
document.querySelector('#undo').onclick=()=>{if(undo.length){redo.push(clone(game));game=undo.pop();render();}};
document.querySelector('#redo').onclick=()=>{if(redo.length){undo.push(clone(game));game=redo.pop();render();}};
document.querySelector('#restart').onclick=()=>change(()=>{game=fresh();game.started=true;});
document.querySelector('#prev').onclick=()=>switchVariant(-1);document.querySelector('#next').onclick=()=>switchVariant(1);
document.addEventListener('keydown',e=>{if(document.querySelector('#modal').open||e.target.closest('input,textarea,select,[contenteditable]'))return;if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();switchVariant(e.key==='ArrowRight'?1:-1);}});
document.querySelector('#close').onclick=()=>document.querySelector('#modal').close();
document.querySelector('#modal').onclick=e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.currentTarget.close();}};
function openDD(){if(!complete())return;if(tableVersion!==version){showModal('原始四手定约表 · 旧结果失效',`<div class="mock-note">原始手牌已变为 v${version}，旧的模拟结果不能继续使用。重新载入示例结果后再查看。</div><div class="modal-actions"><button id="recompute" class="primary">重新载入模拟结果</button></div>`);document.querySelector('#recompute').onclick=()=>{tableVersion=version;document.querySelector('#modal').close();render();openDD();};return;}
 const matrix=[['2S','2S','1S','1S'],['—','—','5H','5H'],['3D','3D','2D','2D'],['2C','2C','3C','3C'],['3NT','3NT','2NT','2NT']];
 showModal('原始四手定约表',`<div class="mock-note">模拟 DDS 数据 · 原始四手 v${tableVersion} · 仅演示表格格式</div><table class="dd-table" aria-label="原始四手定约表"><thead><tr><th>花色 / 庄位</th><th>北</th><th>南</th><th>东</th><th>西</th></tr></thead><tbody>${['♠','♥','♦','♣','NT'].map((s,i)=>`<tr><th class="${[1,2].includes(i)?'red':''}">${s}</th>${matrix[i].map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table><p>格子为该庄位最高可成完整定约；— 表示无法完成一阶定约。</p><p>按原始四手展示，不随后续出牌、收墩、撤销或重走变化。修改原始手牌后结果失效。</p>`);
}
document.querySelector('#dd').onclick=openDD;
document.querySelector('#edit').onclick=()=>{showModal('编辑原始四手 · 共用牌面',`<p>按花色填 AKQJT…；空白 = 未知，- = 已确认缺门。保存会清除当前推演，并使定约表失效，保留教学勾选。</p><div class="editor-grid">${seats.map(s=>`<div class="editor-seat"><h3>${names[s]}家</h3>${suits.map((suit,i)=>`<label><span class="${['H','D'].includes(suit)?'red':''}">${symbols[suit]}</span><input data-edit-seat="${s}" data-edit-suit="${i}" value="${raw[s][i]}" aria-label="${names[s]}家${symbols[suit]}原始手牌"></label>`).join('')}</div>`).join('')}</div><p id="edit-error" class="editor-error"></p><div class="modal-actions"><button id="swap">演示修改：北♠A ↔ 南♠J</button><button id="save-hands" class="primary">保存牌面</button></div>`);
 document.querySelector('#swap').disabled=!raw.N[0].includes('A')||!raw.S[0].includes('J');document.querySelector('#swap').onclick=()=>{document.querySelector('[data-edit-seat="N"][data-edit-suit="0"]').value=raw.N[0].replace('A','J');document.querySelector('[data-edit-seat="S"][data-edit-suit="0"]').value=raw.S[0].replace('J','A');};
 document.querySelector('#save-hands').onclick=()=>{const next=clone(raw);let invalid=false;document.querySelectorAll('[data-edit-seat]').forEach(el=>{const text=el.value.toUpperCase().replace(/10/g,'T').replace(/[\s,]/g,'').replace(/—/g,'-');if(text!==''&&text!=='-'&&[...text].some(r=>!ranks.includes(r)))invalid=true;next[el.dataset.editSeat][el.dataset.editSuit]=text;});const cards=toCards(next),all=seats.flatMap(s=>cards[s]);if(invalid||new Set(all.map(c=>c.id)).size!==all.length||seats.some(s=>cards[s].length!==0&&cards[s].length!==13)){document.querySelector('#edit-error').textContent='请检查：每家输入 13 张（或整手未知），牌点须合法且不能有重复牌。';return;}raw=next;original=cards;version++;tableVersion=null;game=fresh();undo=[];redo=[];shownResults=false;teachingGenerated=false;document.querySelector('#modal').close();render();};};
document.querySelector('#teach').onclick=()=>{teachingGenerated=true;renderTeaching();};
document.querySelector('#settings').onclick=()=>{showModal('模型与连接 · 轻量设置示意','<p>保留现有轻量入口；本轮不比较设置布局。</p><div class="setting-choice"><button class="chosen">6 Luna</button><button>6.1 Sol</button><button>6 Astra</button></div><p>Thinking effort · Medium（示意）</p><div class="mock-note">没有连接 Runtime。模型 effort 列表须在产品实施时按真实能力加载，本页不模拟能力发现。</div><details style="margin-top:15px"><summary>连接设置</summary><p>产品需求：自动查找 Runtime，找不到时支持搜索与手动选择。此原型未实现。</p></details>');document.querySelectorAll('.setting-choice button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.setting-choice button').forEach(x=>x.classList.remove('chosen'));b.classList.add('chosen');});};
render();
